[2017-05-22 16:42:49.072] [ERROR] [default] - user:[aa] coupon.html initialize
[2017-05-31 15:06:47.115] [ERROR] [default] - user:[aa] coupon.html initialize
[2017-06-01 08:27:16.438] [ERROR] [default] - user:[admin] coupon.html initialize
[2017-06-01 10:14:32.213] [ERROR] [default] - user:[admin] coupon.html initialize
[2017-06-01 10:18:44.401] [ERROR] [default] - user:[admin] coupon.html initialize
[2017-06-01 10:26:56.471] [ERROR] [default] - user:[admin] coupon.html initialize
[2017-06-01 10:27:41.372] [ERROR] [default] - user:[admin] coupon.html initialize
[2017-06-01 10:52:01.067] [ERROR] [default] - user:[admin] coupon.html initialize
[2017-06-01 10:53:48.956] [ERROR] [default] - user:[admin] coupon.html initialize
[2017-06-01 13:59:06.730] [ERROR] [default] - user:[admin] SequelizeDatabaseError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
    at Query.formatError (E:\NodejsWorkspace\catch\node_modules\sequelize\lib\dialects\mysql\query.js:175:14)
    at Query._callback (E:\NodejsWorkspace\catch\node_modules\sequelize\lib\dialects\mysql\query.js:49:21)
    at Query.Sequence.end (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query.ErrorPacket (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\sequences\Query.js:88:8)
    at Protocol._parsePacket (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\NodejsWorkspace\catch\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
[2017-06-01 14:23:07.724] [ERROR] [default] - user:[admin] SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'name' in 'field list'
    at Query.formatError (E:\NodejsWorkspace\catch\node_modules\sequelize\lib\dialects\mysql\query.js:175:14)
    at Query._callback (E:\NodejsWorkspace\catch\node_modules\sequelize\lib\dialects\mysql\query.js:49:21)
    at Query.Sequence.end (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query.ErrorPacket (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\sequences\Query.js:88:8)
    at Protocol._parsePacket (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\NodejsWorkspace\catch\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
[2017-06-01 14:23:36.221] [ERROR] [default] - user:[admin] SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'name' in 'field list'
    at Query.formatError (E:\NodejsWorkspace\catch\node_modules\sequelize\lib\dialects\mysql\query.js:175:14)
    at Query._callback (E:\NodejsWorkspace\catch\node_modules\sequelize\lib\dialects\mysql\query.js:49:21)
    at Query.Sequence.end (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query.ErrorPacket (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\sequences\Query.js:88:8)
    at Protocol._parsePacket (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\NodejsWorkspace\catch\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
[2017-06-01 14:24:33.563] [ERROR] [default] - user:[admin] SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'name' in 'field list'
    at Query.formatError (E:\NodejsWorkspace\catch\node_modules\sequelize\lib\dialects\mysql\query.js:175:14)
    at Query._callback (E:\NodejsWorkspace\catch\node_modules\sequelize\lib\dialects\mysql\query.js:49:21)
    at Query.Sequence.end (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query.ErrorPacket (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\sequences\Query.js:88:8)
    at Protocol._parsePacket (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\NodejsWorkspace\catch\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
[2017-06-01 14:38:11.776] [ERROR] [default] - user:[admin] coupon.html initialize
[2017-06-01 14:38:15.870] [ERROR] [default] - user:[admin] coupon.html initialize
[2017-06-01 15:27:20.514] [ERROR] [default] - user:[admin] 传递的机构列表或源机构不合法！
[2017-06-01 15:27:27.571] [ERROR] [default] - user:[admin] 传递的机构列表或源机构不合法！
[2017-06-01 15:28:29.995] [ERROR] [default] - user:[admin] 传递的机构列表或源机构不合法！
[2017-06-01 15:29:04.857] [ERROR] [default] - user:[admin] 传递的机构列表或源机构不合法！
[2017-06-01 15:29:54.812] [ERROR] [default] - user:[admin] 传递的机构列表或源机构不合法！
[2017-06-01 15:30:01.527] [ERROR] [default] - user:[admin] 传递的机构列表或源机构不合法！
[2017-06-01 15:30:12.079] [ERROR] [default] - user:[admin] 传递的机构列表或源机构不合法！
[2017-06-01 15:31:41.801] [ERROR] [default] - user:[admin] 传递的机构列表或源机构不合法！
[2017-06-01 15:31:46.703] [ERROR] [default] - user:[admin] 传递的机构列表或源机构不合法！
[2017-06-01 15:36:44.374] [ERROR] [default] - user:[admin] 传递的机构列表或源机构不合法！
[2017-06-01 15:36:50.777] [ERROR] [default] - user:[admin] 传递的机构列表或源机构不合法！
[2017-06-01 15:37:57.569] [ERROR] [default] - user:[admin] 传递的机构列表或源机构不合法！
[2017-06-01 15:39:53.280] [ERROR] [default] - user:[admin] 传递的机构列表或源机构不合法！
[2017-06-01 15:52:17.545] [ERROR] [default] - TypeError: Cannot read property 'id' of undefined
    at Object.<anonymous> (E:\NodejsWorkspace\catch\bin\www:51:43)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Timeout.Module.runMain [as _onTimeout] (module.js:604:10)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
[2017-06-01 16:07:46.698] [ERROR] [default] - user:[aa] 传递的机构列表或源机构不合法！
[2017-06-02 14:24:51.399] [ERROR] [default] - user:[admin] TOPClientError: Remote service error, code 15; isv.INVALID_JSON_PARAM: JSON参数不合法，只接受字符串值
    at E:\NodejsWorkspace\catch\core\topClient.js:127:23
    at done (E:\NodejsWorkspace\catch\node_modules\urllib\lib\urllib.js:444:5)
    at E:\NodejsWorkspace\catch\node_modules\urllib\lib\urllib.js:693:9
    at decodeContent (E:\NodejsWorkspace\catch\node_modules\urllib\lib\urllib.js:517:14)
    at IncomingMessage.<anonymous> (E:\NodejsWorkspace\catch\node_modules\urllib\lib\urllib.js:658:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[2017-06-02 14:44:26.690] [ERROR] [default] - user:[admin] mobile:[13621700192] send fail:undefined
[2017-06-02 15:33:43.024] [ERROR] [default] - user:[admin] mobile:[13621700192] send fail:undefined
[2017-06-02 15:34:01.455] [ERROR] [default] - user:[admin] mobile:[13621700192] send fail:undefined
[2017-06-05 14:01:00.519] [ERROR] [default] - user:[admin] ReferenceError: couponResults is not defined
    at Model.<anonymous> (E:\NodejsWorkspace\catch\routes\generate.js:126:23)
    at Model.tryCatcher (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
[2017-06-05 14:01:23.132] [ERROR] [default] - user:[admin] ReferenceError: couponResults is not defined
    at Model.<anonymous> (E:\NodejsWorkspace\catch\routes\generate.js:126:23)
    at Model.tryCatcher (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
[2017-06-05 14:02:56.900] [ERROR] [default] - user:[admin] TypeError: Cannot read property 'result' of undefined
    at Model.<anonymous> (E:\NodejsWorkspace\catch\routes\generate.js:142:20)
    at Model.tryCatcher (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
[2017-06-05 14:02:57.016] [ERROR] [default] - TypeError: callback is not a function
    at E:\NodejsWorkspace\catch\core\topClient.js:38:20
    at E:\NodejsWorkspace\catch\core\topClient.js:136:9
    at done (E:\NodejsWorkspace\catch\node_modules\urllib\lib\urllib.js:444:5)
    at E:\NodejsWorkspace\catch\node_modules\urllib\lib\urllib.js:693:9
    at decodeContent (E:\NodejsWorkspace\catch\node_modules\urllib\lib\urllib.js:517:14)
    at IncomingMessage.<anonymous> (E:\NodejsWorkspace\catch\node_modules\urllib\lib\urllib.js:658:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[2017-06-05 14:10:32.432] [ERROR] [default] - user:[admin] TypeError: Cannot read property 'result' of undefined
    at Model.<anonymous> (E:\NodejsWorkspace\catch\routes\generate.js:142:20)
    at Model.tryCatcher (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
[2017-06-05 14:10:47.546] [ERROR] [default] - user:[admin] TypeError: client.executeAsync is not a function
    at Model.<anonymous> (E:\NodejsWorkspace\catch\routes\generate.js:131:27)
    at Model.tryCatcher (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
[2017-06-05 14:14:03.721] [ERROR] [default] - user:[admin] TypeError: client.executeAsync is not a function
    at Model.<anonymous> (E:\NodejsWorkspace\catch\routes\generate.js:131:27)
    at Model.tryCatcher (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
[2017-06-05 14:14:15.394] [ERROR] [default] - user:[admin] TypeError: client.executeAsync is not a function
    at Model.<anonymous> (E:\NodejsWorkspace\catch\routes\generate.js:131:27)
    at Model.tryCatcher (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
[2017-06-05 14:14:51.627] [ERROR] [default] - user:[admin] TypeError: client.executeAsync is not a function
    at Model.<anonymous> (E:\NodejsWorkspace\catch\routes\generate.js:131:27)
    at Model.tryCatcher (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (E:\NodejsWorkspace\catch\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
[2017-06-05 14:18:04.500] [ERROR] [default] - user:[admin] TOPClientError: Remote service error, code 15; isv.TEMPLATE_MISSING_PARAMETERS: 参数缺失，缺少参数：name，模板配置：获得${name}优惠券1张，券码${couponcode}。，传参：{&quot;msgcode&quot;:&quot;1&quot;}
    at E:\NodejsWorkspace\catch\core\topClient.js:127:23
    at done (E:\NodejsWorkspace\catch\node_modules\urllib\lib\urllib.js:444:5)
    at E:\NodejsWorkspace\catch\node_modules\urllib\lib\urllib.js:693:9
    at decodeContent (E:\NodejsWorkspace\catch\node_modules\urllib\lib\urllib.js:517:14)
    at IncomingMessage.<anonymous> (E:\NodejsWorkspace\catch\node_modules\urllib\lib\urllib.js:658:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[2017-06-05 14:26:53.120] [ERROR] [default] - user:[admin] TOPClientError: Remote service error, code 15; isv.PARAM_LENGTH_LIMIT: 变量长度超过限制
    at E:\NodejsWorkspace\catch\core\topClient.js:127:23
    at done (E:\NodejsWorkspace\catch\node_modules\urllib\lib\urllib.js:444:5)
    at E:\NodejsWorkspace\catch\node_modules\urllib\lib\urllib.js:693:9
    at decodeContent (E:\NodejsWorkspace\catch\node_modules\urllib\lib\urllib.js:517:14)
    at IncomingMessage.<anonymous> (E:\NodejsWorkspace\catch\node_modules\urllib\lib\urllib.js:658:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
